# Site settings
title: DyCon Toolbox
description: Welcome to the web interface of DyCon Toolbox, the computational platform developed within the <a href='https://cmc.deusto.eus/dycon/' target='_blank'>ERC DyCon - Dynamic Control</a> project.

dev: true
# command to ignore docs(must be run inside 'docs' folder): git ls-files | tr '\n' ' ' | xargs git update-index --assume-unchanged
# command to STOP ignoring docs(must be run inside 'docs' folder): git ls-files | tr '\n' ' ' | xargs git update-index --no-assume-unchanged


# Secondary Parameters
baseurl: "/dycon-toolbox-documentation" # the subpath of your site, e.g. /blog
url: "https://DeustoTech.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#

gems: [jekyll-mermaid]
mermaid:
  src: 'https://unpkg.com/mermaid@7.1.0/dist/mermaid.js'

destination: docs
header-img: img/home-bg.gif
headercolor: "black"
logo: assets/logo_DyConToolbox_v001.png

# Tertiary Parameters
github_username:  DeustoTech
project_repository: dycon-platform
disqus_shortname: dycon-platform
g-analytics:
altmetric: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.gif"
